# Site settings
site_name: Development
site_url: https://nodesautomations.com/Development/
use_directory_urls: false
# Navigation Tree
nav:
  - Home:
    - docs/index.md
  - CMD: docs/CMD.md
  - Excel: docs/Excel.md
  - Google: docs/Google.md
  - Powerpoint: docs/Powerpoint.md
  - PowerToys: docs/PowerToys.md
  - Reddit: docs/Reddit.md
  - Regular Expressions: docs/Regular Expressions.md
  - Software for Documentations: docs/Software for Documentations.md
  - Staad RCDC: docs/Staad RCDC.md
  - Twitter: docs/Twitter.md
  - Visual Studio Code: docs/Visual Studio Code.md
  - Windows Terminal: docs/Windows Terminal.md
  - Youtube: docs/Youtube.md

# Theme
theme:
  name: material
  logo: assets/favicon.png
  favicon: assets/favicon.png
  # Palette toggle for dark mode
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
          icon: material/brightness-4
          name: Switch to light mode
    - scheme: default
      primary: black
      accent: indigo
      toggle:
          icon: material/brightness-7
          name: Switch to dark mode
  features:
    - content.action.edit # Allows "Edit on GitHub" links
    - content.action.view # Allows "View on GitHub" links
    - content.code.copy # Allows code blocks to have a copy button
    - navigation.path # Enables path navigation top of docs for smaller screens
    - navigation.tabs # Enables tabbed navigation
    - navigation.indexes # Enables attachment of sub section index 
  icon:
    repo: fontawesome/brands/git-alt 
    edit: material/pencil 
    view: material/eye

# Extensions
markdown_extensions:
  - admonition # for Callout boxes
  - pymdownx.highlight: 
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex: # for rendering math equations
      generic: true
  - def_list # List extensions
  - pymdownx.tasklist: # List extensions
      custom_checkbox: true

# Copyright
copyright: Copyright &copy; 2025 Nodes Automations

# Footer social links
extra:
  generator: false # remove "Generated with MkDocs" footer
  social:
    - icon: fontawesome/solid/globe
      link: www.nodesautomations.com
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/NodesAutomations
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/vivekpatel-nodesautomations/
    - icon: fontawesome/brands/github
      link: https://github.com/orgs/NodesAutomations


